#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='\e[2;32m[\e[0m\e[0;31m\u\e[0m\e[2;36m@\e[0m\e[0;35m\h\e[0m\e[2;36m:\e[0m \e[0;34m\W\e[0m\e[2;32m]\e[0m\n>>> '
