# X11
xrdb ~/.Xresources
setxkbmap gb # Uncomment to set keymap to gb layout.

# Feh
#~/.fehbg # Uncomment when using feh backgrounds.

# Pipewire
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/wireplumber &

# Suckless tools
exec slstatus &
exec dwm
